version: '3'
services:
  redis:
    image: redis:alpine3.20
    container_name: shadowcat-ai-redis
    ports:
      - 6379:6379
  mysql:
    image: shadowcat-ai-mysql
    container_name: shadowcat-ai-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345 --execute \"SHOW DATABASES;\""
      interval: 3s 
      timeout: 1s  
      retries: 5   
  phpmyadmin:
    image: phpmyadmin
    container_name: mysql-web-manager
    depends_on:
      - mysql
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
  shadowcat-ai-server:
      depends_on:
        mysql:
          condition: service_healthy
      image: shadowcat-ai-server
      container_name: shadowcat-ai-server
      ports:
        - 8080:8080
        - 8081:8081
      environment:
        - MYSQL_HOST=shadowcat-ai-mysql
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=shadowcat
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=12345
        - REDIS_HOST=shadowcat-ai-redis
        - REDIS_PORT=6379
        - SERVER_PORT=8080
        - CHAT_SERVER_PORT=8081
        - OLLAMA_ADDRESS=localhost
        - OLLAMA_PORT=11434
        - UPLOADS_PATH=uploads
        - INIT_USERNAME=lovelycat
        - INIT_PASSWORD=lovelycat
        - INIT_EMAIL=master@lovelycatv.com
      volumes:
        - D:\Projects\ArtificialIntelligence\shadowcat-ai-server\uploads\:/uploads